module.exports = {
  "Michael Scott": "Steve Carell",
  "Dwight Schrute": "Rainn Wilson",
  "Jim Halpert": "John Krasinski",
  "Pam Beesly": "Jenna Fischer",
  "Ryan Howard": "B.J. Novak",
  "Andy Bernard": "Ed Helms",
  "Robert California": "James Spader",
  "Stanley Hudson": "Leslie David Baker",
  "Kevin Malone": "Brian Baumgartner",
  "Meredith Palmer": "Kate Flannery",
  "Angela Martin": "Angela Kinsey",
  "Oscar Martinez": "Oscar Nunez",
  "Phyllis Lapin": "Phyllis Smith",
  "Roy Anderson": "David Denman",
  "Jan Levinson": "Melora Hardin",
  "Kelly Kapoor": "Mindy Kaling",
  "Toby Flenderson": "Paul Lieberstein",
  "Creed Bratton": "Creed Bratton",
  "Darryl Philbin": "Craig Robinson",
  "Erin Hannon": "Ellie Kemper",
  "Gabe Lewis": "Zach Woods",
  "Holly Flax": "Amy Ryan",
};
